adding TransientTokenGenerator.js
CyberSource/cybersource-rest-client-node pull request #73
Opened 2021-08-04 06:06 UTC by karthikeyankumarskcet

Transient token generator

2021-08-04 06:17 UTC, gnongsie requested changes

2021-08-04 06:17 UTC, gnongsie commented on src/utilities/flex/TransientTokenGenerator.js
> +function TransientTokenGenerator(jwt)
The name should **NOT** be `TransientTokenGenerator`. Change it to `TransientTokenUtility`.

2021-08-04 06:17 UTC, gnongsie commented on src/utilities/flex/TransientTokenGenerator.js
> +module.exports = TransientTokenGenerator;
The name of a function should always be an action, like `verifyToken()` or `parseToken()`.

Change the structure of this file to mimic the same structure of `TokenVerification.js`

2021-08-04 06:54 UTC, gnongsie approved these changes

2021-08-04 06:54 UTC, gnongsie commented
PR is approved. Merge only after getting sign-off from the author, @karthikeyankumarskcet

2023-06-01 15:34 UTC, samhithal commented
@karthikeyankumarskcet can you please confirm if this is what you need?

2023-08-11 08:41 UTC, gnongsie commented
@samhithal : Please note that @karthikeyankumarskcet was a developer working in our team when this PR was created.

It is ok to leave this as is for now.

2025-09-26 06:31 UTC, closed without merging